application: dazzling-rain-655
version: 2014-07-28
runtime: python27
api_version: 1
threadsafe: yes

# To stop api_server.py complaining about images API
libraries:
- name: PIL
  version: latest

handlers:

# Top-level URLs
- url: /$
  static_files: _site/index.html
  upload: _site/index\.html

- url: /(software|publications|research|teaching|contact|cv|about|links|articles)$
  static_files: _site/\1/index.html
  upload: _site/(.*)/index\.html

# Articles
- url: /articles/(.*)$
  static_files: _site/articles/\1/index.html
  upload: _site/articles/(.*)/index\.html

# Bower components
- url: /components/platform/platform.(.*)$
  static_files: js/bower_components/platform/platform.\1
  upload: js/bower_components/platform/platform.(.*)

# Link shortening
- url: /@[^/]*/(new|edit|delete)$
  script: links.application
  login: admin

- url: /@[^/]*$
  script: links.application

# Misc URLs map directly to their path in _site/.
- url: /
  static_dir: _site

# Files to skip
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*.swp
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?node_modules/.*
- ^(.*/)?scripts/.*

